[pytest]
markers =
    math: арифметические тесты
    logic: логические тесты
    exception: тесты на исключения
    boundary: граничные значения
    string: тесты со строками
    arithmetic: альтернативная группа арифметики
